def duel():
    a = str(input("j1"))
    b = str(input("j2"))
    while a > 8 :
        print("non valide")
        a = str(input("j1"))
    while b > 8 :
        print("non valide")
        b = str(input("j1"))
    tempa = 8 - len(a)
    tempb = 8 - len(b)
    print("__________________________________________________________________________________________")
    print("|                                                                                        |")
    print("|  ",a,tempa,"                         | | | | | |                                       |")
    print("|   score :                             ‾   ‾   ‾                                        |")
    print("|                                      | | | | | |                                       |")
    print("|                                       ‾   ‾   ‾                                        |")
    print("|                                      | | | | | |                                       |")
    print("|                                       ‾   ‾   ‾                                        |")
    print("|                                                                                        |")
    print("|                                                                                        |")
    print("|                                                                                        |")
    print("|  ",b,tempb,"                         | | | | | |                                       |")
    print("|   score :                             ‾   ‾   ‾                                        |")
    print("|                                      | | | | | |                                       |")
    print("|                                       ‾   ‾   ‾                                        |")
    print("|                                      | | | | | |                                       |")
    print("|                                       ‾   ‾   ‾                                        |")
    print("|                                                                                        |")
    print("|________________________________________________________________________________________|")